"""Render publication tables and the doctor-agent action space."""

from __future__ import annotations

import argparse
import csv
import json
import os
from collections import defaultdict

DEFAULT_DIR = "taxonomy"

CLASS_ORDER = ["Physical_Examination", "Laboratory", "Imaging", "Pathology", "Physiologic"]
CLASS_LABEL = {
    "Physical_Examination": "Physical examination",
    "Laboratory": "Laboratory tests",
    "Imaging": "Imaging studies",
    "Pathology": "Pathology / microscopy",
    "Physiologic": "Physiologic & functional tests",
}


def read(path):
    with open(path, encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def md_table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default=DEFAULT_DIR)
    ap.add_argument("--top", type=int, default=15, help="rows per class in the L3 preview table")
    a = ap.parse_args()
    D = a.dir

    stats = json.load(open(os.path.join(D, "stats.json"), encoding="utf-8"))
    cats = read(os.path.join(D, "categories_L2.csv"))
    cons = read(os.path.join(D, "concepts_L3.csv"))
    dis = read(os.path.join(D, "diseases_L1_L2.csv"))
    N = stats["n_cases"]
    norm_path = os.path.join(D, "categories_L2_normalized.csv")
    ncats = read(norm_path) if os.path.exists(norm_path) else []
    ncons_path = os.path.join(D, "concepts_L3_normalized.csv")
    ncons = read(ncons_path) if os.path.exists(ncons_path) else []
    onto_path = os.path.join(D, "ontology_stats.json")
    onto = json.load(open(onto_path, encoding="utf-8")) if os.path.exists(onto_path) else None

    space = {
        "n_cases": N,
        "physical_examination": {},
        "diagnostic_tests": {},
        "anatomical_axis": [],
        "disease_axes": {},
    }
    for r in cats:
        if r["L2_category"] == "Unmapped":
            continue
        if r["L1_class"] == "Physical_Examination":
            space["physical_examination"].setdefault(r["L2_category"], [])
        else:
            space["diagnostic_tests"].setdefault(r["L1_class"], {}).setdefault(r["L2_category"], [])
    for r in cons:
        c, l2, l3 = r["L1_class"], r["L2_category"], r["L3_concept"]
        if l2 == "Unmapped" or l3 == "Unmapped":
            continue
        if c == "Physical_Examination":
            space["physical_examination"].setdefault(l2, []).append(l3)
        else:
            space["diagnostic_tests"].setdefault(c, {}).setdefault(l2, []).append(l3)
    anat = sorted(
        {
            r["anatomy_or_specimen"]
            for r in read(os.path.join(D, "test_items.csv"))
            if r["anatomy_or_specimen"]
        }
    )
    space["anatomical_axis"] = anat
    space["disease_axes"] = {
        "icd10_chapter": [
            r["label"]
            for r in dis
            if r["axis"].startswith("ICD-10") and not r["label"].startswith("Unmapped")
        ],
        "clinical_specialty": [r["label"] for r in dis if r["axis"] == "Clinical specialty"],
    }
    for v in space["physical_examination"].values():
        v.sort()
    for sub in space["diagnostic_tests"].values():
        for v in sub.values():
            v.sort()
    with open(os.path.join(D, "action_space.json"), "w", encoding="utf-8") as fh:
        json.dump(space, fh, indent=2, ensure_ascii=False)

    L = []
    L.append("# OSCE action-space taxonomy\n")
    L.append(
        f"Source: `profiles.parquet`, **{N:,} OSCE cases** (one case = one PMC case report).\n"
    )
    L.append(
        "All tables are generated by `taxonomy/build_taxonomy.py` "
        "+ `make_report.py`; the mapping rules live in "
        "`taxonomy/lexicons.py`.\n"
    )

    L.append("\n## Table 1 — Corpus composition\n")
    rows = []
    for c in CLASS_ORDER:
        key = {
            "Physical_Examination": "Physical_Examination_Findings",
            "Laboratory": "Laboratory_Test_Results",
            "Imaging": "Imaging_Results",
            "Pathology": "Pathology_Results",
            "Physiologic": "Physiologic_Test_Results",
        }[c]
        mean_key = "Physical_Examination_findings" if c == "Physical_Examination" else c
        rows.append(
            [
                CLASS_LABEL[c],
                f"{stats['mentions'][c]:,}",
                f"{stats['unique_surface_forms'][c if c != 'Physical_Examination' else 'Physical_Examination_site']:,}",
                f"{stats['section_case_coverage_pct'][key]}%",
                stats["mean_per_case"][mean_key],
            ]
        )
    rows.append(
        [
            "**Total**",
            f"**{sum(stats['mentions'].values()):,}**",
            f"**{sum(stats['unique_surface_forms'].values()):,}**",
            "—",
            "—",
        ]
    )
    L.append(
        md_table(
            [
                "Result section",
                "Findings (mentions)",
                "Unique surface forms",
                "Cases with ≥1 entry",
                "Mean entries / case",
            ],
            rows,
        )
    )
    L.append(
        "\n*Surface forms are the raw generated strings "
        "(`test_name` for tests, `location` for examinations); they are an "
        "open vocabulary and are counted exactly, without normalisation. "
        "The total is a sum over sections — the union over the four test "
        "sections is 35,790 distinct `test_name` strings, since a few "
        "names occur in more than one section.*\n"
    )

    L.append("\n## Table 2 — Taxonomy at four granularities\n")
    ts = stats["taxonomy_size"]
    n_l2 = defaultdict(set)
    n_l3 = defaultdict(set)
    for r in cats:
        if r["L2_category"] != "Unmapped":
            n_l2[r["L1_class"]].add(r["L2_category"])
    for r in cons:
        if r["L2_category"] != "Unmapped" and r["L3_concept"] != "Unmapped":
            n_l3[r["L1_class"]].add(r["L3_concept"])
    n_l2 = {k: len(v) for k, v in n_l2.items()}
    n_l3 = {k: len(v) for k, v in n_l3.items()}
    rows = []
    for c in CLASS_ORDER:
        surf = stats["unique_surface_forms"][
            c if c != "Physical_Examination" else "Physical_Examination_site"
        ]
        rows.append(
            [
                CLASS_LABEL[c],
                n_l2[c],
                n_l3[c],
                f"{surf:,}",
                f"{stats['L2_mapping_coverage_pct_of_mentions'][c]}%",
                f"{stats['L3_mapping_coverage_pct_of_mentions'][c]}%",
            ]
        )
    rows.append(
        [
            "**Total**",
            f"**{sum(n_l2.values())}**",
            f"**{sum(n_l3.values())}**",
            f"**{sum(stats['unique_surface_forms'].values()):,}**",
            "—",
            "—",
        ]
    )
    L.append(
        md_table(
            [
                "L1 class",
                "L2 categories",
                "L3 concepts",
                "L4 surface forms",
                "L2 coverage",
                "L3 coverage",
            ],
            rows,
        )
    )
    L.append(
        "\n*Coverage = share of **mentions** assigned to a named category / "
        "concept rather than the residual `Unmapped` bucket. "
        "L1 = 5 classes. An orthogonal anatomical axis of "
        f"{len(anat)} regions is attached to imaging, pathology and "
        "physiologic entries.*\n"
    )

    L.append("\n## Table 3 — Physical examination (L2, extended set of 18)\n")
    rows = [
        [
            r["L2_category"].replace("_", " "),
            r["n_L3_concepts"],
            f"{int(r['n_L4_surface_forms']):,}",
            f"{int(r['n_mentions']):,}",
            f"{int(r['n_cases']):,}",
            f"{r['pct_cases']}%",
        ]
        for r in cats
        if r["L1_class"] == "Physical_Examination"
    ]
    L.append(
        md_table(
            [
                "Examination system",
                "L3 sites/measures",
                "Surface forms",
                "Findings",
                "Cases",
                "% cases",
            ],
            rows,
        )
    )
    L.append(
        "\n*The generation prompt enumerates 13 examination sections; the "
        "model additionally produced Lymphatic, Genitourinary, "
        "Gynecologic/Obstetric, Oral–Dental and Rectal examinations. "
        "`pe_items.csv` carries both the 18-way extended label and the "
        "13-way prompt label for every row.*\n"
    )

    for c in ["Laboratory", "Imaging", "Pathology", "Physiologic"]:
        L.append(
            f"\n## Table 4{'abcd'[['Laboratory', 'Imaging', 'Pathology', 'Physiologic'].index(c)]} "
            f"— {CLASS_LABEL[c]} (L2)\n"
        )
        rows = [
            [
                r["L2_category"],
                r["n_L3_concepts"],
                f"{int(r['n_L4_surface_forms']):,}",
                f"{int(r['n_mentions']):,}",
                f"{int(r['n_cases']):,}",
                f"{r['pct_cases']}%",
            ]
            for r in cats
            if r["L1_class"] == c
        ]
        L.append(
            md_table(
                ["Category", "L3 concepts", "Surface forms", "Mentions", "Cases", "% cases"], rows
            )
        )

    L.append(f"\n## Table 5 — Most frequent L3 concepts (top {a.top} per class)\n")
    for c in CLASS_ORDER:
        sub = [r for r in cons if r["L1_class"] == c and r["L3_concept"] != "Unmapped"][: a.top]
        L.append(f"\n**{CLASS_LABEL[c]}**\n")
        L.append(
            md_table(
                ["L2 category", "L3 concept", "Surface forms", "Mentions", "% cases"],
                [
                    [
                        r["L2_category"].replace("_", " "),
                        r["L3_concept"],
                        f"{int(r['n_L4_surface_forms']):,}",
                        f"{int(r['n_mentions']):,}",
                        f"{r['pct_cases']}%",
                    ]
                    for r in sub
                ],
            )
        )
    L.append(
        f"\n*Full inventories: `concepts_L3.csv` ({len(cons)} rows) and `categories_L2.csv`.*\n"
    )

    if ncats:
        L.append("\n## Table 5b — Terminology-normalised L2 categories\n")
        L.append(
            "Category names below are the **official display names** of the "
            "cited codes, not free text. A physical examination is a "
            "procedure a clinician performs, so it binds to a SNOMED CT "
            "examination procedure (*Examination of abdomen*), not to a "
            "LOINC document name; the category is keyed on the site "
            "actually examined, so the local `Head_and_Neck` section "
            "resolves to separate scalp, face, neck, ear, nose, mouth and "
            "pharynx examinations. The corresponding LOINC H&P panel is "
            "retained in `pe_items_normalized.csv` as a secondary binding. "
            "Imaging uses DICOM modality codes; laboratory, pathology and "
            "physiologic classes use SNOMED CT discipline procedures.\n"
        )
        for c in CLASS_ORDER:
            rows = [
                [
                    r["L2_category_normalized"],
                    r["code_system"].upper() if r["code_system"] else "—",
                    r["code"] or "—",
                    r["n_L3_concepts"],
                    f"{int(r['n_L4_surface_forms']):,}",
                    f"{int(r['n_mentions']):,}",
                ]
                for r in ncats
                if r["L1_class"] == c
            ]
            if not rows:
                continue
            L.append(f"\n**{CLASS_LABEL[c]}**\n")
            L.append(
                md_table(
                    [
                        "Normalised category",
                        "Code system",
                        "Code",
                        "L3 concepts",
                        "Surface forms",
                        "Mentions",
                    ],
                    rows,
                )
            )
    if onto:
        L.append("\n### Terminology coverage\n")
        L.append(
            md_table(
                ["Class", "% of mentions carrying a code"],
                [
                    [CLASS_LABEL.get(k, k), f"{v}%"]
                    for k, v in onto["coded_pct_of_mentions"].items()
                ],
            )
        )
        L.append(
            "\n"
            + md_table(
                ["Code system", "L3 concepts"],
                [
                    [
                        {
                            "loinc": "LOINC",
                            "sct": "SNOMED CT",
                            "dcm": "DICOM Controlled Terminology",
                        }.get(k, k),
                        v,
                    ]
                    for k, v in sorted(onto["by_code_system"].items())
                ],
            )
        )
        L.append(
            f"\n*{onto['n_concepts']} L3 concepts total: "
            f"{onto['by_match_method'].get('pinned', 0)} hand-asserted codes, "
            f"{onto['by_match_method'].get('search', 0)} resolved by "
            "terminology-server search, "
            f"{onto['by_match_method'].get('panel_fallback', 0)} rolled up to "
            "their LOINC examination panel, "
            f"{onto['by_match_method'].get('unmapped', 0)} with no published "
            "concept (5 of these are the residual `Unmapped` buckets). "
            "Every code was resolved against a live terminology server; "
            "`concept_ontology.csv` shows the local label beside the "
            "official display name for inspection.*\n"
        )

    d = stats["diseases"]
    L.append("\n## Table 6 — Disease label granularity\n")
    L.append(
        md_table(
            ["Granularity", "Distinct labels", "Provenance"],
            [
                [
                    "L4 — free-text diagnosis",
                    f"{d['unique_free_text_diagnosis']:,}",
                    "verbatim `diagnosis` field",
                ],
                [
                    "L3 — normalised disease name",
                    f"{d['unique_orpha_name']:,}",
                    "`orpha_name` field",
                ],
                ["L2 — ICD-10 code", f"{d['unique_icd10_codes']:,}", "Orphanet→ICD-10 crosswalk"],
                [
                    "L1 — ICD-10 chapter",
                    f"{d['icd10_chapters_used']}",
                    "derived from the ICD-10 code",
                ],
                [
                    "L1' — clinical specialty",
                    f"{d['specialty_groups']}",
                    f"{d['raw_specialty_strings']} raw `specialty` strings, rule-normalised",
                ],
            ],
        )
    )
    L.append(
        f"\n*{d['orpha_crosswalk_matched_pct']}% of cases "
        f"({d['orpha_crosswalk_matched_cases']:,}/{N:,}) resolve to an "
        "Orphanet record by exact name or synonym match; "
        f"{d['icd10_mapped_pct_of_cases']}% carry an ICD-10 code "
        "(the remainder are Orphanet entries with no ICD-10 cross-reference, "
        "or common diseases absent from the rare-disease nomenclature).*\n"
    )

    L.append("\n### Table 6a — ICD-10 chapter distribution\n")
    L.append(
        md_table(
            ["ICD-10 chapter", "Title", "Cases", "% cases"],
            [
                [
                    r["axis"].replace("ICD-10 chapter ", ""),
                    r["label"],
                    f"{int(r['n_cases']):,}",
                    f"{r['pct_cases']}%",
                ]
                for r in dis
                if r["axis"].startswith("ICD-10")
            ],
        )
    )

    L.append("\n### Table 6b — Clinical specialty distribution\n")
    L.append("*Cases are multi-labelled; percentages sum to >100%.*\n")
    L.append(
        md_table(
            ["Specialty group", "Cases", "% cases"],
            [
                [r["label"], f"{int(r['n_cases']):,}", f"{r['pct_cases']}%"]
                for r in dis
                if r["axis"] == "Clinical specialty"
            ],
        )
    )

    pb = stats["post_baseline"]
    L.append(
        "\n## Table 7 — Post-baseline findings (not part of the initial ordering action space)\n"
    )
    L.append(
        md_table(
            ["Section", "Mentions"],
            [[k, f"{v:,}"] for k, v in pb["by_section"]]
            + [["**Total**", f"**{pb['mentions']:,}**"]],
        )
    )
    L.append("\n" + md_table(["Phase", "Mentions"], [[k, f"{v:,}"] for k, v in pb["by_phase"]]))
    L.append(
        "\n*These are results that appear only after treatment or at "
        "follow-up. They must be withheld from a diagnostic agent's "
        "observation space at ordering time.*\n"
    )

    L.append("\n## Method & limitations\n")
    L.append(
        "1. **Surface normalisation** (`lexicons.normalise`) is deterministic: "
        "NFKC, parenthetical removal, case folding, intra-word hyphen "
        "flattening, British→US spelling, and removal of timing/ordinal "
        "qualifiers (`initial`, `follow-up`, `patient 2`, …). It is "
        "identity-preserving — it never merges two different tests.\n"
        "2. **L2/L3 assignment** uses ordered regular-expression lexicons, "
        "first match wins, applied to the normalised `test_name` concatenated "
        "with the panel-level `modality` field where present. Ordering is "
        "specimen-before-analyte, so `24-hour urinary protein` resolves to a "
        "urine study rather than to serum protein.\n"
        "3. **Coverage is reported, not assumed.** Entries no rule matches stay "
        "in an explicit `Unmapped` bucket and are counted in Table 2; the "
        "residual is a long tail of singleton eponyms and study-specific assays.\n"
        "4. **Terminology binding.** Category and concept names are the official "
        "display names of LOINC, SNOMED CT and DICOM codes, resolved live "
        "against the HL7 public FHIR terminology server (`tx.fhir.org`, LOINC "
        "2.82 / SNOMED CT International 2025-02-01) and the NLM Clinical Table "
        "Search Service. Codes marked `pinned` in `concept_ontology.csv` were "
        "asserted and then verified; codes marked `search` were resolved by "
        "terminology search and are **representative exemplars of the class, "
        "not exact equivalents** (e.g. the IHC CD-marker class resolves to a "
        "single CD-marker LOINC term). Use the local L3 label as the class "
        "identity and the code as its terminology anchor. Concept boundaries "
        "(e.g. echocardiography counted under both `Imaging` and `Physiologic`, "
        "because the generator emits it in both sections) follow the dataset's "
        "own section assignment.\n"
        "5. **Disease chapter assignment inherits Orphanet's ICD-10 "
        "cross-references**, most of which are `NTBT` (Orphanet term narrower "
        "than the ICD-10 code). Chapter-level roll-up is therefore sound; "
        "code-level identity is not.\n"
    )

    with open(os.path.join(D, "summary.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")
    print("wrote", os.path.join(D, "summary.md"))
    print("wrote", os.path.join(D, "action_space.json"))


if __name__ == "__main__":
    main()
