"""Crosswalk from the local taxonomy labels to published terminology codes."""

from __future__ import annotations


PE_SITE_TO_EXAM = {
    "General appearance / habitus": "162673000",
    "Unspecified site": "5880005",
    "Unspecified (patient-level label)": "5880005",
    "Lateralised body region": "5880005",
    "Growth / development": "395691005",
    "Anthropometry": "61746007",
    "Vital signs (composite)": "61746007",
    "Vital signs measured at bedside": "61746007",
    "Blood pressure": "61746007",
    "Heart rate / pulse": "61746007",
    "Respiratory rate": "61746007",
    "Body temperature": "61746007",
    "Oxygen saturation": "61746007",
    "Body mass index": "61746007",
    "Body weight": "61746007",
    "Body height / length": "61746007",
    "Head circumference": "61746007",
    "Body circumference": "61746007",
    "Capillary refill time": "61746007",
    "Pain score": "61746007",
    "Growth percentile": "61746007",
    "Glasgow coma scale": "82856007",
    "Skin / cutaneous lesion": "271303006",
    "Skin appendages (hair / nails)": "284420002",
    "Head / scalp": "395121000",
    "Face / jaw": ("loinc", "32432-7"),
    "Neck / thyroid": "457601000124102",
    "Ear / hearing": "225670007",
    "Nose / nasal cavity": "274794006",
    "Oral cavity / dentition": "39868003",
    "Pharynx / larynx": "164771005",
    "Eye - general / orbit": "36228007",
    "Eye - anterior segment / adnexa": "36228007",
    "Eye - posterior segment": "36228007",
    "Pupils": "36228007",
    "Vision / ocular motility": "36228007",
    "Chest / lungs": "268925001",
    "Heart / precordium": "284448002",
    "Jugular venous pressure": "363003006",
    "Peripheral vasculature": "363003006",
    "Breast": "46662001",
    "Abdomen": "225162003",
    "Liver": "225162003",
    "Spleen": "225162003",
    "Kidney / renal angle": "225162003",
    "Anorectal / perineum": "410007005",
    "External genitalia / pelvis": "268945009",
    "Bladder / urinary tract": "268945009",
    "Lymph nodes": "284427004",
    "Spine / back": "284394000",
    "Joints": "284393006",
    "Muscles": "284433008",
    "Bones / skeletal": "363215001",
    "Limbs / extremities": "302773001",
    "Neurologic examination (composite)": "84728005",
    "Cranial nerves": "274786004",
    "Motor system": "274793000",
    "Reflexes": "163778008",
    "Sensory system": "274796008",
    "Gait / coordination": "274787008",
    "Meningeal signs": "84728005",
    "Mental status / consciousness / speech": "392257007",
    "Mental state / behaviour": "392257007",
}

PE_SITE_TO_CATEGORY = {
    "General appearance / habitus": "162673000",
    "Unspecified site": "5880005",
    "Unspecified (patient-level label)": "5880005",
    "Lateralised body region": "5880005",
    "Growth / development": "162673000",
    "Anthropometry": "61746007",
    "Vital signs (composite)": "61746007",
    "Vital signs measured at bedside": "61746007",
    "Blood pressure": "61746007",
    "Heart rate / pulse": "61746007",
    "Respiratory rate": "61746007",
    "Body temperature": "61746007",
    "Oxygen saturation": "61746007",
    "Body mass index": "61746007",
    "Body weight": "61746007",
    "Body height / length": "61746007",
    "Head circumference": "61746007",
    "Body circumference": "61746007",
    "Capillary refill time": "61746007",
    "Pain score": "61746007",
    "Growth percentile": "61746007",
    "Glasgow coma scale": "84728005",
    "Skin / cutaneous lesion": "271303006",
    "Skin appendages (hair / nails)": "271303006",
    "Head / scalp": "395121000",
    "Face / jaw": ("loinc", "32432-7"),
    "Neck / thyroid": "457601000124102",
    "Ear / hearing": "225670007",
    "Nose / nasal cavity": "274794006",
    "Oral cavity / dentition": "39868003",
    "Pharynx / larynx": "164771005",
    "Eye - general / orbit": "36228007",
    "Eye - anterior segment / adnexa": "36228007",
    "Eye - posterior segment": "36228007",
    "Pupils": "36228007",
    "Vision / ocular motility": "36228007",
    "Chest / lungs": "268925001",
    "Heart / precordium": "363003006",
    "Jugular venous pressure": "363003006",
    "Peripheral vasculature": "363003006",
    "Breast": "46662001",
    "Abdomen": "225162003",
    "Liver": "225162003",
    "Spleen": "225162003",
    "Kidney / renal angle": "225162003",
    "Anorectal / perineum": "410007005",
    "External genitalia / pelvis": "268945009",
    "Bladder / urinary tract": "268945009",
    "Lymph nodes": "284427004",
    "Spine / back": "363215001",
    "Joints": "363215001",
    "Muscles": "363215001",
    "Bones / skeletal": "363215001",
    "Limbs / extremities": "363215001",
    "Neurologic examination (composite)": "84728005",
    "Cranial nerves": "84728005",
    "Motor system": "84728005",
    "Reflexes": "84728005",
    "Sensory system": "84728005",
    "Gait / coordination": "84728005",
    "Meningeal signs": "84728005",
    "Mental status / consciousness / speech": "392257007",
    "Mental state / behaviour": "392257007",
}

PE_SITE_TO_PANEL = {
    "General appearance / habitus": "8713-0",
    "Unspecified site": "8713-0",
    "Unspecified (patient-level label)": "8713-0",
    "Lateralised body region": "8713-0",
    "Growth / development": "8713-0",
    "Anthropometry": "34565-2",
    "Vital signs (composite)": "8716-3",
    "Vital signs measured at bedside": "8716-3",
    "Blood pressure": "8716-3",
    "Heart rate / pulse": "8716-3",
    "Respiratory rate": "8716-3",
    "Body temperature": "8716-3",
    "Oxygen saturation": "8716-3",
    "Body mass index": "34565-2",
    "Body weight": "34565-2",
    "Body height / length": "34565-2",
    "Head circumference": "34565-2",
    "Body circumference": "34565-2",
    "Capillary refill time": "8716-3",
    "Pain score": "8716-3",
    "Glasgow coma scale": "8705-6",
    "Growth percentile": "34565-2",
    "Skin / cutaneous lesion": "8709-8",
    "Skin appendages (hair / nails)": "8709-8",
    "Head / scalp": "8701-5",
    "Face / jaw": "8701-5",
    "Neck / thyroid": "11442-1",
    "Ear / hearing": "8698-3",
    "Nose / nasal cavity": "8706-4",
    "Oral cavity / dentition": "8704-9",
    "Pharynx / larynx": "8704-9",
    "Eye - general / orbit": "8699-1",
    "Eye - anterior segment / adnexa": "8699-1",
    "Eye - posterior segment": "8699-1",
    "Pupils": "8699-1",
    "Vision / ocular motility": "8699-1",
    "Chest / lungs": "11443-9",
    "Heart / precordium": "11421-5",
    "Jugular venous pressure": "11421-5",
    "Peripheral vasculature": "11421-5",
    "Breast": "32422-8",
    "Abdomen": "8694-2",
    "Liver": "8694-2",
    "Spleen": "8694-2",
    "Kidney / renal angle": "8694-2",
    "Anorectal / perineum": "8708-0",
    "External genitalia / pelvis": "8700-7",
    "Bladder / urinary tract": "8700-7",
    "Lymph nodes": "11448-8",
    "Spine / back": "11441-3",
    "Joints": "11441-3",
    "Muscles": "11441-3",
    "Bones / skeletal": "11441-3",
    "Limbs / extremities": "8703-1",
    "Neurologic examination (composite)": "8705-6",
    "Cranial nerves": "8705-6",
    "Motor system": "8705-6",
    "Reflexes": "8705-6",
    "Sensory system": "8705-6",
    "Gait / coordination": "8705-6",
    "Meningeal signs": "8705-6",
    "Mental status / consciousness / speech": "8693-4",
    "Mental state / behaviour": "8693-4",
}

PE_SITE_PIN = {
    "Skin / cutaneous lesion": ("loinc", "8709-8"),
    "Head / scalp": ("loinc", "32469-9"),
    "Spine / back": ("loinc", "32476-4"),
    "Chest / lungs": ("loinc", "32449-1"),
    "Ear / hearing": ("loinc", "32437-6"),
    "Pharynx / larynx": ("loinc", "32463-2"),
    "Oral cavity / dentition": ("loinc", "32439-2"),
    "Limbs / extremities": ("loinc", "8703-1"),
    "Blood pressure": ("loinc", "85354-9"),
    "Heart rate / pulse": ("loinc", "8867-4"),
    "Respiratory rate": ("loinc", "9279-1"),
    "Body temperature": ("loinc", "8310-5"),
    "Oxygen saturation": ("loinc", "59408-5"),
    "Body mass index": ("loinc", "39156-5"),
    "Body weight": ("loinc", "29463-7"),
    "Body height / length": ("loinc", "8302-2"),
    "Head circumference": ("loinc", "9843-4"),
    "Glasgow coma scale": ("loinc", "9269-2"),
    "Capillary refill time": ("loinc", "44963-7"),
    "Mental status / consciousness / speech": ("loinc", "8693-4"),
    "Mental state / behaviour": ("loinc", "8693-4"),
}

PE_SITE_QUERY = {
    "Pupils": "Physical findings of Pupil",
    "Eye - anterior segment / adnexa": "Physical findings of Cornea",
    "Vision / ocular motility": "Physical findings of Vision",
    "Joints": "Physical findings of Joint",
    "Muscles": "Physical findings of Muscle",
    "Nose / nasal cavity": "Physical findings of Nose",
    "Face / jaw": "Physical findings of Face",
    "Neck / thyroid": "Physical findings of Neck",
    "Abdomen": "Physical findings of Abdomen",
    "Liver": "Physical findings of Liver",
    "Spleen": "Physical findings of Spleen",
    "Breast": "Physical findings of Breast",
    "Anorectal / perineum": "Physical findings of Rectum",
    "External genitalia / pelvis": "Physical findings of Genitalia",
    "Reflexes": "Physical findings of Neurologic deep tendon reflexes",
    "Gait / coordination": "Physical findings of Neurologic balance and Coordination",
    "Cranial nerves": "Physical findings of Cranial nerves",
    "Skin appendages (hair / nails)": "Physical findings of Nail",
    "Bones / skeletal": "Physical findings of Bone",
}


LAB_PIN = {
    "Hemoglobin": "718-7",
    "Hematocrit": "4544-3",
    "White blood cell count": "6690-2",
    "Platelet count": "777-3",
    "Red blood cell count": "789-8",
    "Erythrocyte sedimentation rate": "4537-7",
    "C-reactive protein": "1988-5",
    "Procalcitonin": "33959-8",
    "Reticulocyte count": "17849-1",
    "Complete blood count": "58410-2",
    "Leukocyte differential": "24318-8",
    "Red cell indices": "30428-7",
    "Prothrombin time / INR": "5902-2",
    "Activated partial thromboplastin time": "14979-9",
    "Fibrinogen": "3255-7",
    "D-dimer": "48065-7",
    "Renal function (creatinine / urea)": "24362-6",
    "Serum electrolytes": "24326-1",
    "Calcium / phosphate / magnesium": "17861-6",
    "Uric acid": "3084-1",
    "Liver function tests": "24325-3",
    "Albumin / total protein": "1751-7",
    "Protein electrophoresis / immunofixation": "13980-8",
    "Lactate dehydrogenase": "2532-0",
    "Creatine kinase": "2157-6",
    "Cardiac biomarkers": "42757-5",
    "Hemoglobin A1c": "4548-4",
    "Blood glucose": "2345-7",
    "Glucose tolerance test": "20438-8",
    "Lipid profile": "24331-1",
    "Pancreatic enzymes (amylase / lipase)": "1798-8",
    "Iron studies / ferritin": "2276-4",
    "Vitamin B12 / folate": "2132-9",
    "Arterial / venous blood gas": "24336-0",
    "Lactate / pyruvate / ammonia": "2524-7",
    "Basic / comprehensive metabolic panel": "24323-8",
    "Angiotensin-converting enzyme": "2742-5",
    "Thyroid function tests": "24348-5",
    "Parathyroid hormone": "2731-8",
    "Vitamin D": "1989-3",
    "Prolactin": "2842-3",
    "Calcitonin": "1992-7",
    "Erythropoietin": "2237-6",
    "Urinalysis": "24356-8",
    "Blood culture": "600-7",
    "Urine culture": "630-4",
    "HIV testing": "75622-1",
    "Antinuclear antibody": "5048-4",
    "Rheumatoid factor / anti-CCP": "11572-5",
    "Complement levels": "4485-9",
    "Alpha-fetoprotein": "1834-1",
    "Carcinoembryonic antigen": "2039-6",
    "Prostate-specific antigen": "2857-1",
    "Human chorionic gonadotropin": "19080-1",
    "Flow cytometry / immunophenotyping": ("sct", "64444005"),
    "Karyotype / cytogenetics": "29770-5",
    "Semen analysis": "13361-1",
    "Bone marrow examination": ("sct", "167907006"),
    "Peripheral blood smear": ("sct", "104130000"),
    "Serum immunoglobulins": "34550-4",
    "Cerebrospinal fluid analysis": ("sct", "252392005"),
    "Blood group / compatibility": "882-1",
    "Cancer antigen (CA 19-9 / 125 / 15-3)": "24108-3",
    "Adrenal axis (cortisol / ACTH)": "2143-6",
    "Gonadal / reproductive hormones": "15067-2",
    "Cytokine / soluble marker assay": "26881-3",
    "Coagulation studies": "34529-8",
    "Fluorescence in situ hybridization": ("sct", "426329006"),
    "Other molecular genetic testing": ("sct", "405825005"),
    "Other autoantibodies": ("sct", "314067002"),
    "Pedigree / segregation analysis": ("sct", "410551005"),
    "Drug levels / toxicology": ("sct", "30058000"),
    "Enzyme activity assay": ("sct", "122444009"),
    "Other tumor markers": ("sct", "250724005"),
    "Allergy testing": ("sct", "252512005"),
    "Stool studies": ("sct", "252393000"),
    "Sputum / BAL studies": ("sct", "397397002"),
    "Stain microscopy (Gram / AFB)": ("sct", "391245000"),
}

LAB_QUERY = {
    "Unspecified laboratory workup": "Laboratory studies",
    "Unspecified hematology workup": "Hematology studies",
    "Unspecified hormonal workup": "Endocrine studies",
    "Unspecified immunological workup": "sct:immunology laboratory test",
    "Quantitative urine studies": "24 hour Urine protein",
    "Serous / synovial fluid analysis": "Cell count and differential panel Body fluid",
    "Hemolysis / hemoglobinopathy workup": "Hemoglobinopathy panel",
    "Thyroid autoantibodies": "Thyroperoxidase antibody",
    "Growth hormone / IGF-1": "Insulin-like growth factor-I",
    "Renin / aldosterone": "Aldosterone renin ratio",
    "Catecholamines / metanephrines": "Metanephrine Urine",
    "Pancreatic / gut hormones": "Insulin Serum or Plasma",
    "Extractable nuclear antigen antibodies": "Extractable nuclear Ab",
    "ANCA": "Neutrophil cytoplasmic antibody",
    "Antiphospholipid antibodies": "Cardiolipin antibody",
    "Liver autoantibodies": "Mitochondrial antibody",
    "Celiac serology": "Tissue transglutaminase antibody",
    "Neurologic / renal autoantibodies": "Acetylcholine receptor antibody",
    "Antistreptolysin O titre": "Streptolysin O antibody",
    "HLA typing": "HLA-B27",
    "Cryoglobulins": "Cryoglobulin Serum",
    "Inflammatory markers (composite)": "sct:acute phase reactant measurement",
    "Other microbiological culture": "Bacteria identified in Specimen by Culture",
    "Tuberculin skin test / IGRA": "Mycobacterium tuberculosis interferon gamma release",
    "Viral hepatitis serology": "Hepatitis panel",
    "Syphilis serology": "Treponema pallidum antibody",
    "Pathogen nucleic-acid testing": "sct:nucleic acid amplification",
    "Infectious serology": "sct:serologic test",
    "Parasitology": "Ova and parasites identified in Stool",
    "Fungal testing": "Fungus identified in Specimen by Culture",
    "Exome / genome / panel sequencing": "Whole exome sequence analysis",
    "Targeted gene sequencing": "Gene mutation analysis",
    "Chromosomal microarray": "Chromosome analysis microarray",
    "Targeted molecular assay (MLPA / methylation)": "Methylation analysis",
    "Metabolic screen (amino / organic acids)": "sct:amino acid measurement",
    "Trace metals / ceruloplasmin": "Ceruloplasmin Serum or Plasma",
    "Research / specialised assay": "Laboratory studies",
    "Aspiration cytology": "sct:fine needle aspiration",
}


IMAGING_PIN = {
    "CT": ("dcm", "CT"),
    "High-resolution CT": ("dcm", "CT"),
    "CT angiography": ("dcm", "CT"),
    "Cone-beam CT": ("dcm", "CT"),
    "CT myelography": ("dcm", "CT"),
    "MRI": ("dcm", "MR"),
    "Diffusion MRI": ("dcm", "MR"),
    "Functional MRI": ("dcm", "MR"),
    "MR angiography": ("dcm", "MR"),
    "MR venography": ("dcm", "MR"),
    "MR spectroscopy": ("dcm", "MR"),
    "MRCP": ("dcm", "MR"),
    "Ultrasound": ("dcm", "US"),
    "Doppler ultrasound": ("dcm", "US"),
    "Elastography": ("dcm", "US"),
    "Endoscopic ultrasound": ("dcm", "US"),
    "Intravascular ultrasound": ("dcm", "IVUS"),
    "Ocular ultrasound / UBM": ("dcm", "US"),
    "Echocardiography": ("dcm", "US"),
    "Transthoracic echocardiography": ("dcm", "US"),
    "Transesophageal echocardiography": ("dcm", "US"),
    "Stress echocardiography": ("dcm", "US"),
    "Fetal echocardiography": ("dcm", "US"),
    "Radiography": ("dcm", "CR"),
    "Panoramic radiograph": ("dcm", "PX"),
    "Cephalometric radiograph": ("dcm", "CR"),
    "Skeletal survey": ("dcm", "CR"),
    "Bone age assessment": ("dcm", "CR"),
    "Mammography": ("dcm", "MG"),
    "Bone densitometry": ("dcm", "BMD"),
    "Fluoroscopy": ("dcm", "RF"),
    "Contrast fluoroscopy (barium)": ("dcm", "RF"),
    "Urographic contrast study": ("dcm", "RF"),
    "Hysterosalpingography": ("dcm", "RF"),
    "Myelography": ("dcm", "RF"),
    "Arthrography": ("dcm", "RF"),
    "Cholangiography": ("dcm", "RF"),
    "Other contrast study": ("dcm", "RF"),
    "Catheter angiography": ("dcm", "XA"),
    "Coronary angiography": ("dcm", "XA"),
    "Digital subtraction angiography": ("dcm", "XA"),
    "Ventriculography": ("dcm", "XA"),
    "Venography": ("dcm", "XA"),
    "Lymphangiography": ("dcm", "XA"),
    "Cardiac catheterization": ("dcm", "XA"),
    "PET": ("dcm", "PT"),
    "PET/CT": ("dcm", "PT"),
    "PET/MRI": ("dcm", "PT"),
    "SPECT": ("dcm", "NM"),
    "SPECT/CT": ("dcm", "NM"),
    "Bone scintigraphy": ("dcm", "NM"),
    "Thyroid scintigraphy": ("dcm", "NM"),
    "Renal scintigraphy": ("dcm", "NM"),
    "Hepatobiliary scintigraphy": ("dcm", "NM"),
    "Myocardial perfusion scintigraphy": ("dcm", "NM"),
    "Receptor-targeted scintigraphy": ("dcm", "NM"),
    "Lymphoscintigraphy": ("dcm", "NM"),
    "Inflammation scintigraphy": ("dcm", "NM"),
    "Other scintigraphy": ("dcm", "NM"),
    "Fundus photography": ("dcm", "OP"),
    "Fundus autofluorescence": ("dcm", "OP"),
    "Fluorescein angiography": ("dcm", "OP"),
    "Indocyanine green angiography": ("dcm", "OP"),
    "Optical coherence tomography": ("dcm", "OPT"),
    "OCT angiography": ("dcm", "OPT"),
    "Anterior-segment imaging": ("dcm", "OP"),
    "Dermoscopy": ("dcm", "XC"),
    "Clinical photography": ("dcm", "XC"),
    "Confocal microscopy (in vivo)": ("dcm", "GM"),
    "Colonoscopy": ("sct", "73761001"),
    "Sigmoidoscopy": ("sct", "44441009"),
    "Bronchoscopy": ("sct", "10847001"),
    "Laparoscopy": ("sct", "73632009"),
    "Arthroscopy": ("sct", "13714004"),
    "ERCP": ("sct", "386718000"),
    "Other endoscopy": ("dcm", "ES"),
    "ENT endoscopy": ("dcm", "ES"),
    "Proctoscopy / anoscopy": ("dcm", "ES"),
    "Capsule endoscopy / enteroscopy": ("dcm", "ES"),
    "Thoracoscopy / mediastinoscopy": ("dcm", "ES"),
    "Unspecified imaging": ("sct", "363679005"),
    "Other imaging modality": ("sct", "363679005"),
}

IMAGING_L2_MODALITY = {
    "Computed tomography": "CT",
    "Magnetic resonance imaging": "MR",
    "Ultrasonography": "US",
    "Echocardiography": "US",
    "Radiography & fluoroscopy": "CR",
    "Nuclear medicine": "NM",
    "Catheter angiography": "XA",
    "Endoscopy": "ES",
    "Ophthalmic imaging": "OP",
    "Mammography": "MG",
    "Dermatologic imaging": "XC",
    "Other imaging": "OT",
}

L2_PIN = {
    ("Laboratory", "Clinical chemistry"): ("sct", "166312007"),
    ("Laboratory", "Hematology"): ("sct", "33468001"),
    ("Laboratory", "Microbiology & infectious serology"): ("sct", "19851009"),
    ("Laboratory", "Urinalysis & body fluids"): ("sct", "27171005"),
    ("Laboratory", "Immunology & autoimmune serology"): ("sct", "252318005"),
    ("Laboratory", "Coagulation"): ("sct", "3116009"),
    ("Laboratory", "Flow cytometry / immunophenotyping"): ("sct", "64444005"),
    ("Laboratory", "Molecular genetics & cytogenetics"): ("sct", "405825005"),
    ("Laboratory", "Tumor markers"): ("sct", "250724005"),
    ("Laboratory", "Toxicology & drug monitoring"): ("sct", "314076009"),
    ("Laboratory", "Metabolic & biochemical genetics"): ("sct", "395118002"),
    ("Laboratory", "General / unspecified laboratory"): ("sct", "15220000"),
    ("Pathology", "Histopathology"): ("sct", "252416005"),
    ("Pathology", "Immunohistochemistry"): ("sct", "117617002"),
    ("Pathology", "Cytopathology"): ("sct", "1348332002"),
    ("Pathology", "Gross pathology"): ("sct", "168126000"),
    ("Pathology", "Electron microscopy"): ("sct", "73512001"),
    ("Pathology", "Immunofluorescence"): ("sct", "127796002"),
    ("Pathology", "Hematopathology (bone marrow)"): ("sct", "167907006"),
    ("Pathology", "Hematopathology (blood film)"): ("sct", "104130000"),
    ("Pathology", "Molecular / in-situ pathology"): ("sct", "405825005"),
    ("Pathology", "Other microscopy"): ("sct", "117259009"),
    ("Pathology", "Other pathology"): ("sct", "39228008"),
    ("Physiologic", "Cardiac electrophysiology & monitoring"): ("sct", "276341003"),
    ("Physiologic", "Echocardiography & cardiac imaging"): ("loinc", "34552-0"),
    ("Physiologic", "Pulmonary function & exercise testing"): ("sct", "23426006"),
    ("Physiologic", "Ophthalmic function testing"): ("sct", "36228007"),
    ("Physiologic", "Invasive hemodynamics & pressure monitoring"): ("sct", "716777001"),
    ("Physiologic", "Audiovestibular testing"): ("sct", "21727005"),
    ("Physiologic", "Urodynamics"): ("sct", "252895004"),
    ("Physiologic", "Neurocognitive & psychometric assessment"): ("sct", "1999007"),
}

IMAGING_QUERY = {
    "Esophagogastroduodenoscopy": "sct:esophagogastroduodenoscopy",
    "Cystoscopy / ureteroscopy": "sct:cystoscopy",
    "Hysteroscopy": "sct:hysteroscopy",
}


PATHOLOGY_PIN = {
    "Histopathology (H&E)": ("sct", "252416005"),
    "Frozen section": ("sct", "817011007"),
    "Autopsy examination": ("sct", "29240004"),
    "Peripheral blood smear": ("sct", "104130000"),
    "Cytology (unspecified)": ("sct", "1348332002"),
    "Other cytologic preparation": ("sct", "1348332002"),
    "Other pathology examination": ("sct", "39228008"),
    "Iron stain": ("sct", "117241006"),
    "Direct immunofluorescence": ("sct", "127796002"),
    "Immunofluorescence (unspecified)": ("sct", "127796002"),
    "Bone marrow aspirate / smear": ("sct", "49401003"),
    "Bone marrow trephine biopsy": ("sct", "56241004"),
    "Cervical (Pap) cytology": ("loinc", "19765-7"),
    "Polarized / phase-contrast microscopy": ("sct", "117259009"),
    "Fluorescence / confocal microscopy": ("sct", "117259009"),
}

PATHOLOGY_QUERY = {
    "Gross / macroscopic pathology": "sct:macroscopic examination",
    "Light microscopy": "sct:light microscopy",
    "Electron microscopy": "sct:electron microscopy",
    "Transmission electron microscopy": "sct:transmission electron microscopy",
    "Scanning electron microscopy": "sct:scanning electron microscopy",
    "IHC - other / unspecified": "sct:immunohistochemistry",
    "IHC - CD marker panel": "CD antigen Tissue by Immune stain",
    "IHC - proliferation index (Ki-67)": "Ki-67 Tissue by Immune stain",
    "IHC - epithelial markers": "Cytokeratin Tissue by Immune stain",
    "IHC - melanocytic markers": "S100 Tissue by Immune stain",
    "IHC - mesenchymal / muscle markers": "Desmin Tissue by Immune stain",
    "IHC - neural / neuroendocrine markers": "Synaptophysin Tissue by Immune stain",
    "IHC - hormone receptors / HER2": "Estrogen receptor Tissue by Immune stain",
    "IHC - prognostic / predictive markers": "p53 Tissue by Immune stain",
    "Fine-needle aspiration cytology": "sct:fine needle aspiration",
    "Body-fluid cytology": "Cytology report Body fluid",
    "Bone marrow examination": "sct:bone marrow examination",
    "PAS stain": "sct:periodic acid Schiff stain",
    "Congo red stain": "sct:Congo red stain",
    "Silver / fungal stain": "sct:silver stain",
    "Acid-fast stain": "sct:acid fast stain",
    "Gram stain": "sct:Gram stain",
    "Connective-tissue stain": "sct:trichrome stain",
    "Lipid stain": "sct:fat stain",
    "Mucin stain": "sct:mucicarmine stain",
    "Other special / histochemical stain": "sct:special stain",
    "FISH on tissue": "sct:fluorescence in situ hybridization",
    "In-situ hybridization": "sct:in situ hybridization",
    "Molecular pathology": "sct:molecular genetic test",
}


PHYSIO_PIN = {
    "Six-minute walk test": ("sct", "252478000"),
    "Fractional flow reserve": ("sct", "371842003"),
    "Electrocardiogram": ("loinc", "11524-6"),
    "Echocardiography": ("loinc", "34552-0"),
    "Electroencephalography": ("loinc", "11523-8"),
    "Pulse oximetry": ("loinc", "59408-5"),
    "Blood gas / capnography": ("loinc", "24336-0"),
    "Peak expiratory flow": ("loinc", "33452-4"),
    "Visual acuity": ("loinc", "70936-0"),
    "Intraocular pressure": ("loinc", "56844-4"),
}

PHYSIO_QUERY = {
    "Ambulatory ECG monitoring": "sct:ambulatory electrocardiographic monitoring",
    "Cardiac device / EP study": "sct:cardiac electrophysiologic study",
    "Head-up tilt table test": "sct:tilt table test",
    "Cardiotocography": "sct:fetal heart rate monitoring",
    "Right heart catheterization": "sct:right heart catheterization",
    "Invasive hemodynamic study": "sct:hemodynamic monitoring",
    "Cardiac functional assessment (unspecified)": "sct:cardiac function study",
    "Blood-pressure / CVP monitoring": "sct:central venous pressure monitoring",
    "Ankle-brachial index": "sct:ankle brachial index",
    "Electromyography": "sct:electromyography",
    "Nerve conduction study": "sct:nerve conduction study",
    "Polysomnography / sleep study": "sct:polysomnography",
    "CSF opening pressure": "sct:lumbar puncture",
    "Visual evoked potentials": "sct:visual evoked potential",
    "Somatosensory evoked potentials": "sct:somatosensory evoked potential",
    "Brainstem auditory evoked potentials": "sct:auditory brainstem response",
    "Other evoked potentials": "sct:evoked potential",
    "Autonomic function testing": "sct:autonomic function studies",
    "Cellular electrophysiology (research)": "sct:electrophysiologic study",
    "Spirometry": "sct:spirometry",
    "Body plethysmography": "sct:plethysmography",
    "Diffusing capacity (DLCO)": "sct:carbon monoxide diffusing capacity",
    "Exercise stress testing": "sct:exercise tolerance test",
    "Pulmonary function test (composite)": "sct:pulmonary function test",
    "Bronchial challenge / reversibility": "sct:bronchial provocation test",
    "Visual field / perimetry": "sct:visual field test",
    "Refraction": "sct:refraction",
    "Electroretinography": "sct:electroretinography",
    "Electro-oculography": "sct:electro-oculography",
    "Other psychophysical vision test": "sct:color vision test",
    "Ocular motility / orthoptic assessment": "sct:ocular motility study",
    "Ocular surface testing": "sct:Schirmer",
    "Audiometry": "sct:audiometry",
    "Tympanometry": "sct:tympanometry",
    "Otoacoustic emissions": "sct:otoacoustic emission",
    "Vestibular testing": "sct:vestibular function test",
    "Manometry": "sct:manometry",
    "pH / impedance monitoring": "sct:esophageal pH",
    "GI transit / motility study": "sct:gastric emptying study",
    "Breath test": "sct:breath test",
    "Urodynamic study": "sct:urodynamic",
    "Sweat chloride test": "sct:sweat test",
    "Cognitive screening (MMSE / MoCA)": "sct:mini mental state examination",
    "Intelligence testing": "sct:intelligence test",
    "Developmental assessment": "sct:developmental assessment",
    "Neuropsychological battery": "sct:neuropsychological assessment",
    "Clinical rating scale / questionnaire": "sct:assessment using assessment scale",
    "Gait / posture analysis": "sct:gait assessment",
    "Musculoskeletal functional testing": "sct:muscle strength test",
    "Fluid-balance monitoring": "sct:fluid balance monitoring",
    "Allergy / provocation testing": "sct:allergy skin test",
    "Pharmacologic / provocative bedside test": "sct:provocation test",
    "Other physiologic test": "sct:physiological test",
}
